sudo: false
language: node_js
node_js:
- iojs
before_script:
- git config --global user.email "iamstarkov+tachikombie@gmail.com"
- git config --global user.name "Tachikoma Zombie"
- git remote rm origin
- git remote add origin https://iamstarkov:${GH_TOKEN}@github.com/iamstarkov/jsunderhood.git
after_script:
- npm run f5
- npm run save
- npm run deploy
