sudo: false
language: node_js
node_js:
- iojs
before_script:
- git config --global user.email "iamstarkov+tachikombie@gmail.com"
- git config --global user.name "Tachikoma Zombie"
- git remote rm origin
- git remote add origin https://iamstarkov:${GH_TOKEN}@github.com/iamstarkov/jsunderhood.git
after_script:
- npm run f5
- npm run save
- npm run deploy
env:
  global:
    secure: pPw6XxnDCf4QmNRR3+13p8kfyvvtOrTbzwuwgv948axfxLLbmJOx9mpw6OyMDQFKBZ3S3jviLSIKzy2vRWOK2CT5rhYw6kLbe56lqChki/og2yhukm3nyJpjwPttq9cPoisJ4KGJ3q8Wtat0GAnCVgyr09/8ouJRg5HWxHIaz/CDSCZJ5GhSuAQlb0QqVzN7sQHfe5CSLkodizsNjgVSJB6kH/NT0fBKxGZnXLDZypy24LoOS4w6J+mUQZDJjwwPHC4zJDtCjU+zqRmmlRDaEO3z5px/PjaljG9gc4v7eiqf8oLiiQl32/iSbearE9fvRMSGJyhFozoevEOMT1Y8xBxs3xOtjC19rHeFIiByiaPkJ9Dv5Nz9MFc/mqK7ERrLu41AUxjmiFav+QvFmqLR2Azg5qib9iVhIKTLre61nDBhCtf2C7A3EJf0rfWhVIKe67DmPlbhZn1wqFqY0MQnLOiAZP0l1IpE/iJ+hvCR4U/LeQB/3mFcLyOwLALPv3pT92CdP9cf6a00t1KZfMKIOMPeZWUP1H7ttl4QF97rjYlN9wF16ANMZaLp8ImrtjZfBBzT70cvYh4R/65iFopHL4nnH4EHFUblLgTSBy2r26tzuHOnfY34aK7YpVerKFhqqfwEmqUrW4msXzSyAKr3zuUTPC/weR94c1BdTHwH/hI=
